### ISSUE TITLE
Userland grouping packages

### ISSUE THREAD

**Issue by jycouet** [antfu/node-modules-inspector#51]
### Clear and concise description of the problem

Today, package.json is kinda messy because you get a flat list of all your deps.
So it's hard to know why you have this and that dep (or devDep) `depth 1`.

### Suggested solution

What about grouping packages by feature ? 

Imagine a file like: `package.json.why` that would look like:
```yaml
grouping:
  - name: linting
    comment: I like to have clean code
    list:
      - '@eslint/compat'
      - '@eslint/js'
      - 'eslint'
      - 'eslint-config-prettier'
      - 'eslint-plugin-svelte'
      - 'globals'
      - 'typescript-eslint'

  - name: sveltekit
    list:
      - '@sveltejs/adapter-node'
      - '@sveltejs/kit'
      - '@sveltejs/vite-plugin-svelte'

  - name: svelte
    list:
      - 'svelte'
      - 'svelte-check'

  - name: ui
    comment: All UI related things
    list:
      - 'tailwindcss'
      - '@tailwindcss/vite'
      - '@tailwindcss/typography'
      - 'daisyui'

  - name: testing
    list:
      - 'vitest'
      - 'jsdom'
```

And in the `UI`, you could: 
- See the "cost" of a feature
- See deps that are not linked to any feature
- Add comment why this and that are needed
- Edit this file to help you organize your deps

---

It's maybe not directly linked with `node-modules-inspector`, I'm about to do something to solve this `userland` issue and was thinking to propose it here first. Feel free to tell me that it's not in scope. 😊

### Validations

- [x] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I like this idea but it would be a lot of work to implement that. I am open to PRs 👀

**Comment by OrbisK** [comment]
The `package.json.why` reminds me a bit of the [`pnpm catalogue`](https://pnpm.io/catalogs). Maybe we can use them somehow?

like that:

```yml
catalogs:
  # Can be referenced through "catalog:linting"
  linting:
    @eslint/compat: ...
    @eslint/compat: ...
    ...

  # Can be referenced through "catalog:testing"
  testing:
    vitest: ...
    jsdom: ...
```

**Comment by jycouet** [comment]
Was not aware of this, thx for sharing.
I'll play with this first 👍

**Comment by jycouet** [comment]
It's probably better than creating yet another file but it's a pnpm feature only.

Let's see. Where it will end up.

---

Next level is to say "I want linting", and it's pulling the 4 deps (defined somewhere).
I'm mixing topics, but this is the real deal in userland.
Head is 🤯

**Comment by OrbisK** [comment]
> It's probably better than creating yet another file but it's a pnpm feature only.

I had the same thought, BUT maybe other package managers will implement this at some point AND while those features are not there, we should just fall back on the same structure. So we can have it for free with pnpm and we can do the `package.json.why` as `whatever.yml` (better naming here) and have the same schema as `pnpm-workspace.yml`.

So if we implement the "package why" file, we can do it in a `pnpm-workspace` compartible way.

For the structure of `whatever.yml` for non-pnpm package managers, we might even drop the version numbers to avoid having to maintain them. Like this:

```yml
# pnpm-workspace
catalogs:
  linting:
    @eslint/compat: ^x.y.z
    @eslint/compat: latest
```
might be simplified to
```yml
# whatever.yml (non-pnpm)
catalogs:
  linting:
    @eslint/compat:
    @eslint/compat:
```
